# Generated by Django 4.1.4 on 2022-12-07 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 12, 7, 21, 35, 9, 167370)
            ),
        ),
    ]
